### ISSUE TITLE
(Feature request) Implement the winit frontend

### ISSUE THREAD

**Issue by hardBSDk** [evmar/retrowin32#32]
It will be an Rust alternative for SDL2, the winit crate support many operating systems, from desktop to mobile.

**Comment by evmar** [comment]
One reason I picked SDL is that I also eventually want to make sound work.  So until winit support is important for some purpose or until someone wants to write a patch for it, I don't think I need to track this in the tracker.  

The way things currently work is there is a [cli 'host'](https://github.com/evmar/retrowin32/blob/main/cli/src/host.rs) that implements platform bits like file IO, and it expects a `GUI` impl that is implemented in [the module that contains all of the SDL code](https://github.com/evmar/retrowin32/blob/main/cli/src/sdl.rs), so if you wanted to write this you could try following that.
