### ISSUE TITLE
(Question) Does sound is supported?

### ISSUE THREAD

**Issue by hardBSDk** [evmar/retrowin32#33]

**Comment by evmar** [comment]
There's a skeleton of winmm.dll (used by older apps) [here](https://github.com/evmar/retrowin32/blob/main/win32/src/winapi/winmm/wave.rs), and even more of a skeleton of dsound.dll [here](https://github.com/evmar/retrowin32/blob/main/win32/src/winapi/dsound.rs).  Neither get close to making any sound, they are just enough to get some sound-making programs not crash.  There's a lot to figure out to get sound working, including threads.
