### ISSUE TITLE
vcruntime140 memset should return dst but returns 0

### ISSUE THREAD

**Issue by ethteck** [evmar/retrowin32#9]
As per https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/memset-wmemset?view=msvc-170#return-value

https://github.com/evmar/retrowin32/blob/main/win32/src/winapi/vcruntime140.rs#L26

(Found by https://github.com/encounter/)

**Comment by encounter** [comment]
Yep, just peeking at some of the DLL impls and noticed.
